select
  {{ string_cast('session_id') }} as session_id,
  cast(session_date as date) as session_date,
  {{ string_cast('user_pseudo_id') }} as user_pseudo_id,
  {{ nullable_string('user_id') }} as user_id,
  {{ timestamp_cast('session_start_at') }} as session_start_at,
  {{ timestamp_cast('session_end_at') }} as session_end_at,
  {{ string_cast('landing_page') }} as landing_page,
  {{ nullable_string('landing_content_id') }} as landing_content_id,
  lower({{ string_cast('source') }}) as source,
  lower({{ string_cast('medium') }}) as medium,
  {{ nullable_string('campaign_id') }} as campaign_id,
  lower({{ string_cast('device_category') }}) as device_category,
  {{ string_cast('browser') }} as browser,
  {{ string_cast('operating_system') }} as operating_system,
  {{ string_cast('country') }} as country,
  {{ string_cast('region') }} as region,
  cast(event_count as bigint) as event_count,
  cast(engagement_time_msec as bigint) as engagement_time_msec,
  {{ bool_cast('is_engaged_session') }} as is_engaged_session,
  {{ bool_cast('is_converted_session') }} as is_converted_session,
  cast(order_count as bigint) as order_count,
  {{ money_cast('session_revenue') }} as session_revenue,
  {{ timestamp_cast('created_at') }} as created_at
from {{ raw_relation('fact_sessions') }}
